"""
Django settings for forensic_project project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return str(value).strip().lower() in {"1", "true", "yes", "on"}


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'change-me-in-prod')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = [h.strip() for h in os.getenv('DJANGO_ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if h.strip()]

try:
    from decouple import config
except ImportError:
    def config(name, default=''):
        return os.getenv(name, default)
 
# ─── API Keys (read from .env) ───────────────────────────────
GEMINI_API_KEY        = config('GEMINI_API_KEY', default='')
GOOGLE_VISION_API_KEY = config('GOOGLE_VISION_API_KEY', default='')
 
# Pass to environment so ai_detector.py can read them
import os
os.environ.setdefault('GEMINI_API_KEY',        GEMINI_API_KEY)
os.environ.setdefault('GOOGLE_VISION_API_KEY', GOOGLE_VISION_API_KEY)




# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'cases',           # ← ADD
    'evidence',        # ← ADD
    'reconstruction',  # ← ADD
    'accounts',        # ← ADD

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'forensic_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',                   # ← for index.html (homepage)
            BASE_DIR / 'django_app' / 'templates',    # ← for login.html
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',

            
            ],
        },
    },
]
WSGI_APPLICATION = 'forensic_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', '').strip().lower()
if DB_ENGINE == 'postgresql':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', ''),
            'USER': os.getenv('DB_USER', ''),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'localhost'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('DB_NAME') or Path(BASE_DIR) / 'db.sqlite3',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static'] if (BASE_DIR / 'static').exists() else []
# ─── Media (evidence uploads) ─────────────────────────────────
import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
 
MEDIA_URL  = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = "/dashboard/"          # change to your home/dashboard URL
LOGOUT_REDIRECT_URL = '/login/'


# Evidence upload and local-first detection controls.
EVIDENCE_MAX_UPLOAD_SIZE = int(os.getenv('EVIDENCE_MAX_UPLOAD_SIZE', 10 * 1024 * 1024))
EVIDENCE_ALLOWED_IMAGE_FORMATS = tuple(
    fmt.strip().upper()
    for fmt in os.getenv('EVIDENCE_ALLOWED_IMAGE_FORMATS', 'JPEG,PNG,WEBP,BMP').split(',')
    if fmt.strip()
)
EVIDENCE_MIN_IMAGE_WIDTH = int(os.getenv('EVIDENCE_MIN_IMAGE_WIDTH', 16))
EVIDENCE_MIN_IMAGE_HEIGHT = int(os.getenv('EVIDENCE_MIN_IMAGE_HEIGHT', 16))
EVIDENCE_MAX_IMAGE_PIXELS = int(os.getenv('EVIDENCE_MAX_IMAGE_PIXELS', 40_000_000))
ENABLE_CV_CANDIDATES = env_bool('ENABLE_CV_CANDIDATES', True)
AUTO_ANALYZE_ON_UPLOAD = env_bool('AUTO_ANALYZE_ON_UPLOAD', False)
ENABLE_GEMINI_BACKUP = env_bool('ENABLE_GEMINI_BACKUP', False)
ENABLE_ROBOFLOW_DETECTION = env_bool('ENABLE_ROBOFLOW_DETECTION', False)
ENABLE_YOLO_WORLD_FALLBACK = env_bool('ENABLE_YOLO_WORLD_FALLBACK', False)
GEMINI_MODEL = os.getenv('GEMINI_MODEL', 'gemini-2.0-flash')
SERVE_MEDIA_FILES = env_bool('DJANGO_SERVE_MEDIA', True)
FORENSIC_WEAPON_WEIGHTS = os.getenv('FORENSIC_WEAPON_WEIGHTS', '')
FORENSIC_BLOOD_WEIGHTS = os.getenv('FORENSIC_BLOOD_WEIGHTS', '')
FORENSIC_FINGERPRINT_WEIGHTS = os.getenv('FORENSIC_FINGERPRINT_WEIGHTS', '')
FORENSIC_FOOTPRINT_WEIGHTS = os.getenv('FORENSIC_FOOTPRINT_WEIGHTS', '')
FORENSIC_TRACE_WEIGHTS = os.getenv('FORENSIC_TRACE_WEIGHTS', '')
FORENSIC_COMBINED_WEIGHTS = os.getenv('FORENSIC_COMBINED_WEIGHTS', '')
FORENSIC_NMS_IOU_THRESHOLD = float(os.getenv('FORENSIC_NMS_IOU_THRESHOLD', '0.55'))
FORENSIC_YOLO_IMAGE_SIZE = int(os.getenv('FORENSIC_YOLO_IMAGE_SIZE', '768'))
FORENSIC_CLASS_THRESHOLDS = {
    'blood_stain': float(os.getenv('FORENSIC_CONF_BLOOD_STAIN', '0.35')),
    'fingerprint': float(os.getenv('FORENSIC_CONF_FINGERPRINT', '0.40')),
    'footprint': float(os.getenv('FORENSIC_CONF_FOOTPRINT', '0.40')),
    'grenade': float(os.getenv('FORENSIC_CONF_GRENADE', '0.35')),
    'gun': float(os.getenv('FORENSIC_CONF_GUN', '0.35')),
    'knife': float(os.getenv('FORENSIC_CONF_KNIFE', '0.30')),
}

ENABLE_NEURAL_DEPTH = env_bool('ENABLE_NEURAL_DEPTH', True)
ENABLE_OPEN3D_RECONSTRUCTION = env_bool('ENABLE_OPEN3D_RECONSTRUCTION', True)
ALLOW_3D_FALLBACK = env_bool('ALLOW_3D_FALLBACK', False)
RECON_MAX_DIM = int(os.getenv('RECON_MAX_DIM', '1024'))
RECON_POISSON_DEPTH = int(os.getenv('RECON_POISSON_DEPTH', '9'))
RECON_VOXEL_SIZE = float(os.getenv('RECON_VOXEL_SIZE', '0.02'))
RECON_MESH_SMOOTH_ITERATIONS = int(os.getenv('RECON_MESH_SMOOTH_ITERATIONS', '2'))


# ─── Logging (useful for API debugging) ───────────────────────
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {'class': 'logging.StreamHandler'},
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'evidence.ai_detector': {'level': 'DEBUG', 'handlers': ['console']},
        'reconstruction.views': {'level': 'DEBUG', 'handlers': ['console']},
    },
}
 
