# Generated by Django 4.2.6 on 2026-05-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images/%Y/%m/')),
                ('image_filename', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('annotated_image', models.ImageField(blank=True, null=True, upload_to='results/annotated/%Y/%m/')),
                ('detections_json', models.TextField(default='[]')),
                ('total_objects', models.IntegerField(default=0)),
                ('overall_risk', models.CharField(choices=[('none', 'None'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='none', max_length=20)),
                ('weapons_found', models.BooleanField(default=False)),
                ('detection_summary', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_set', to='cases.case')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
