# Generated by Django 4.2.6 on 2026-05-20 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0001_initial'),
        ('evidence', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evidence',
            options={'ordering': ['-analyzed_at']},
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='created_at',
            new_name='analyzed_at',
        ),
        migrations.RenameField(
            model_name='evidence',
            old_name='detections_json',
            new_name='detections',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='annotated_image',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='detection_summary',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='image_filename',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='overall_risk',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='processed',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='total_objects',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='weapons_found',
        ),
        migrations.AddField(
            model_name='evidence',
            name='summary',
            field=models.TextField(default='{}'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='threat_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evidence_items', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='image',
            field=models.ImageField(upload_to='evidence_uploads/'),
        ),
    ]
