# Generated by Django 4.2.6 on 2026-06-07 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('evidence', '0002_alter_evidence_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidence',
            name='detections',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='image',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='threat_level',
        ),
        migrations.AddField(
            model_name='evidence',
            name='file',
            field=models.ImageField(blank=True, default='', upload_to='evidence/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='file_size',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='evidence',
            name='original_filename',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('analyzed', 'Analyzed'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='analyzed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='DetectionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detections_json', models.TextField(default='[]')),
                ('scene_summary', models.TextField(blank=True, default='')),
                ('evidence_count', models.IntegerField(default=0)),
                ('scene_type', models.CharField(default='unknown', max_length=50)),
                ('sources_used', models.CharField(blank=True, default='', max_length=100)),
                ('analyzed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('evidence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='evidence.evidence')),
            ],
        ),
    ]
