# Generated by Django 4.2.6 on 2026-06-26 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0004_analysisrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='analysis_duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='annotated_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='candidate_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='confirmed_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='detections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='error_state',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='source_models',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='evidence',
            name='analysis_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='analysis_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='evidence',
            name='analysis_image_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='evidence',
            name='analysis_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='evidence',
            name='model_versions',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='evidence',
            name='original_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('analyzed', 'Analyzed'), ('failed', 'Failed'), ('flagged', 'Flagged')], default='pending', max_length=20),
        ),
    ]
