# Generated by Django 4.2.6 on 2026-06-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0006_request_workflow_and_result_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='detectionresult',
            name='class_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='footprint_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='grenade_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='gun_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='detectionresult',
            name='knife_count',
            field=models.IntegerField(default=0),
        ),
    ]
