# Generated by Django 4.2.6 on 2026-06-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='auditlog',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='object_id',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registered'), ('approved', 'User Approved'), ('role_changed', 'Role Changed'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_deleted', 'Case Deleted'), ('evidence_upload', 'Evidence Uploaded'), ('evidence_delete', 'Evidence Deleted'), ('analysis_run', 'Analysis Run'), ('report_download', 'Report Downloaded')], max_length=30),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('investigator', 'Investigator'), ('analyst', 'Analyst')], default='investigator', max_length=20),
        ),
    ]
