# Generated by Codex on 2026-06-28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_systemsetting_auditlog_model_name_auditlog_object_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('database_engine', models.CharField(max_length=120)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('checksum_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], default='success', max_length=20)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('user', 'User'), ('case', 'Case'), ('analysis', 'Analysis'), ('reconstruction', 'Reconstruction'), ('report', 'Report'), ('backup', 'Backup'), ('system', 'System')], default='system', max_length=30)),
                ('related_object_type', models.CharField(blank=True, default='', max_length=80)),
                ('related_object_id', models.CharField(blank=True, default='', max_length=80)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('login', 'User Login'), ('logout', 'User Logout'), ('register', 'User Registered'), ('approved', 'User Approved'), ('role_changed', 'Role Changed'), ('case_created', 'Case Created'), ('case_updated', 'Case Updated'), ('case_deleted', 'Case Deleted'), ('evidence_upload', 'Evidence Uploaded'), ('evidence_delete', 'Evidence Deleted'), ('analysis_run', 'Analysis Run'), ('request_submitted', 'Analysis Request Submitted'), ('request_approved', 'Analysis Request Approved'), ('request_rejected', 'Analysis Request Rejected'), ('reconstruction_run', 'Reconstruction Run'), ('report_generated', 'Report Generated'), ('report_download', 'Report Downloaded'), ('backup_created', 'Backup Created')], max_length=30),
        ),
    ]
