# Generated by Django 4.2.6 on 2026-05-12 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('evidence', '0001_initial'),
        ('cases', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SceneReconstruction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ply_file', models.FileField(blank=True, null=True, upload_to='scenes/pointclouds/%Y/%m/')),
                ('depth_map', models.ImageField(blank=True, null=True, upload_to='scenes/depthmaps/%Y/%m/')),
                ('scene_name', models.CharField(blank=True, max_length=255)),
                ('total_points', models.IntegerField(default=0)),
                ('num_clusters', models.IntegerField(default=0)),
                ('clusters_json', models.JSONField(blank=True, default=list)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconstructions', to='cases.case')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconstructions', to='evidence.evidence')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
