# Generated by Django 4.2.6 on 2026-06-30 16:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evidence', '0007_detectionresult_class_counts_and_more'),
        ('reconstruction', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenereconstruction',
            name='analysis_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scene_reconstruction', to='evidence.analysisrequest'),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='glb_file',
            field=models.FileField(blank=True, null=True, upload_to='scenes/pointclouds/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='mesh_type',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='model_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='model_version',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='output_sha256',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='parameters_json',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='triangle_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scenereconstruction',
            name='vertex_count',
            field=models.IntegerField(default=0),
        ),
    ]
