import json

from django.contrib.auth.models import User
from django.test import TestCase
from django.urls import reverse

from accounts.models import Notification
from cases.models import Case
from cases import report_views
from evidence.models import Evidence


class CasePermissionTests(TestCase):
    def setUp(self):
        self.admin = User.objects.create_superuser("admin", "admin@example.com", "pass12345")
        self.user = User.objects.create_user("investigator", password="pass12345")
        self.user.profile.is_approved = True
        self.user.profile.save(update_fields=["is_approved"])
        self.other = User.objects.create_user("other", password="pass12345")
        self.other.profile.is_approved = True
        self.other.profile.save(update_fields=["is_approved"])
        self.case = Case.objects.create(title="Assigned", case_number="CASE-1", created_by=self.admin, assigned_to=self.user)
        self.other_case = Case.objects.create(title="Hidden", case_number="CASE-2", created_by=self.admin, assigned_to=self.other)
        Evidence.objects.create(case=self.case, uploaded_by=self.user, original_filename="one.jpg")
        Evidence.objects.create(case=self.other_case, uploaded_by=self.other, original_filename="two.jpg")

    def test_normal_user_cannot_create_case(self):
        self.client.login(username="investigator", password="pass12345")
        response = self.client.post(
            reverse("case-list"),
            data=json.dumps({"title": "Nope"}),
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 403)

    def test_assigned_user_sees_only_assigned_cases(self):
        self.client.login(username="investigator", password="pass12345")
        response = self.client.get(reverse("case-list"))
        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertEqual(len(payload), 1)
        self.assertEqual(payload[0]["case_number"], "CASE-1")

    def test_dashboard_counts_are_user_scoped(self):
        self.client.login(username="investigator", password="pass12345")
        response = self.client.get(reverse("stats"))
        self.assertEqual(response.status_code, 200)
        payload = response.json()
        self.assertEqual(payload["total_cases"], 1)
        self.assertEqual(payload["total_evidence"], 1)

    def test_case_assignment_notification_goes_to_assigned_user_only(self):
        self.client.login(username="admin", password="pass12345")
        response = self.client.post(
            reverse("case-list"),
            data=json.dumps({
                "title": "New Assigned",
                "case_number": "CASE-3",
                "assigned_to_id": self.user.id,
            }),
            content_type="application/json",
        )
        self.assertEqual(response.status_code, 200)
        self.assertTrue(Notification.objects.filter(user=self.user, title="Case assigned").exists())
        self.assertFalse(Notification.objects.filter(user=self.admin, title="Case assigned").exists())

    def test_user_generated_report_notifies_admin_not_user(self):
        if not report_views.REPORTLAB_OK:
            self.skipTest("reportlab is not installed")
        self.client.login(username="investigator", password="pass12345")

        response = self.client.get(reverse("case_report", args=[self.case.id]))

        self.assertEqual(response.status_code, 200)
        self.assertTrue(Notification.objects.filter(user=self.admin, title="User generated report").exists())
        self.assertFalse(Notification.objects.filter(user=self.user, title="User generated report").exists())

    def test_admin_generated_report_notifies_assigned_user_not_admin(self):
        if not report_views.REPORTLAB_OK:
            self.skipTest("reportlab is not installed")
        self.client.login(username="admin", password="pass12345")

        response = self.client.get(reverse("case_report", args=[self.case.id]))

        self.assertEqual(response.status_code, 200)
        self.assertTrue(Notification.objects.filter(user=self.user, title="Report generated by admin").exists())
        self.assertFalse(Notification.objects.filter(user=self.admin, title="Report generated by admin").exists())
